### ISSUE TITLE
Sugerencias

### ISSUE THREAD

**Issue by appwebd** [flowcl/PHP-API-CLIENT#5]
Hola sres. flow.cl, considerar como sugerencias las modificaciones realizadas en:

https://github.com/appwebd/PHP-API-CLIENT/branches

![Screenshot_2019-11-05 appwebd PHP-API-CLIENT](https://user-images.githubusercontent.com/20527169/68252314-f693ba80-0003-11ea-900a-baa84b2ae651.png)

**Comment by flowcl** [comment]
Muchas gracias por la sugerencias.
